version: "3.8"

services:
  asterisk:
    image: kr4ge/avr-asterisk:latest
    container_name: asterisk
    ports:
      - "5038:5038"
      - "5060:5060/udp"
      - "10000-20000:10000-20000/udp"
      - "8088:8088"
    networks:
      - avrnw
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/httpstatus"]
      interval: 10s
      timeout: 5s
      retries: 5
